CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE CLIENT(
	ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
	FIRST_NAME VARCHAR(128),
	LAST_NAME VARCHAR(128),
	EMAIL VARCHAR(64) NOT NULL UNIQUE,
	PASSWORD TEXT,
	ACTIVE BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE JOURNAL(
	ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
	OWNER_ID UUID,
	POSTED_DATE TIMESTAMP,
	MODE INT2,
	TITLE VARCHAR(256),
	BODY TEXT,
	CONSTRAINT CLIENT_FK FOREIGN KEY (OWNER_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE
);

CREATE TABLE PROMPT(
    ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
    MODE INT2,
    PROMPT TEXT
);

CREATE TABLE VERIFICATION_TOKEN(
    ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
    TOKEN VARCHAR(256) NOT NULL UNIQUE,
    CLIENT_ID UUID NOT NULL,
    EXPIRY_DATE TIMESTAMP,
    CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID) ON DELETE CASCADE
);