CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USERS(
	ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
	FIRST_NAME VARCHAR(128),
	LAST_NAME VARCHAR(128),
	EMAIL VARCHAR(64) NOT NULL UNIQUE,
	PASSWORD TEXT
);

CREATE TABLE JOURNALS(
	ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
	USER_ID UUID,
	POSTED_DATE TIMESTAMP,
	MODE INT2,
	TITLE VARCHAR(256),
	BODY TEXT,
	CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE PROMPTS(
    ID UUID DEFAULT public.uuid_generate_v4() PRIMARY KEY,
    MODE INT2,
    PROMPT TEXT
);